<?php

//hook_init()
// function customsignup_init(){
//     drupal_set_message("Hi this is my custom form");
// }

//hook_menu()
function customsignup_menu(){
    $items=array();
    $items['customsignup'] = array(
        'title' => "Mo's custom form",
        'description' => 'Custom form',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('customsignup_showForm'),
        'access callback' => 'user_access',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM
    );

    return $items;
}


//function call to display form
//this function was passed in the page arguments array in the hook_menu() function
function customsignup_showForm(){
    $form=array();

    $form['username'] = array(
        '#type' => 'textfield',
        '#title' => t('Username'),
        '#default_value' => '',
        '#size' => 30,
        '#maxlength' => 128,
        '#required' => TRUE,

    );

    $form['email'] = array(
        '#type' => 'textfield',
        '#title' => t('Email'),
        '#default_value' => '',
        '#size' => 30,
        '#maxlength' => 128,
        '#required' => TRUE,
    );
   
    $form['password'] = array(
        '#type' => 'textfield',
        '#title' => t('Password'),
        '#default_value' => '',
        '#size' => 30,
        '#maxlength' => 128,
        '#required' => TRUE,
      
    );

    $form['submit']=array(
        '#type'=>'submit',
        '#value'=>'Submit',
        
    );
    $form['#submit'][] = 'customsignup_showForm_submit';
    return $form;
}

//will validate the field email to determine if an int was passed
// function customsignup_form_validate($form, &$form_state){
    
//     $query = db_select('users', 'u')
//     ->fields('u', array('uid'))
//     ->condition('u.mail', $form_state['values']['email'])
//     ->execute();
//     $result = $query->fetch();

//     if($result->u){
//         return FALSE;
//     }
//     return TRUE;
// }

//function call that will perform actions when the submit button in showForm() is clicked.
function customsignup_showForm_submit($form, &$form_state){
    //calling validate function before proceeding to submit to database
    $validated = customsignup_form_validate($form, $form_state);
    if($validated == FALSE){
        form_set_error('email', t('That email already has an account'));
    }
    if($validated == TRUE){
        $new_user = array(
            'name' => $form_state['values']['username'],
            'pass' => $form_state['values']['password'], //no need to md5 hash drupal function does this
            'mail' => $form_state['values']['email'],
            'status' => 1,
            'init' => $form_state['values']['email'],
            'roles' => array(5)
        );

        user_save('', $new_user);
        drupal_set_message(t('Account created successfully'));
    }
}

